INSERT INTO RENT_STATION(id, city, street) VALUES (1, 'London', 'Low Street 33');
INSERT INTO RENT_STATION(id, city, street) VALUES (2, 'Paris', 'Random Street 95');
INSERT INTO RENT_STATION(id, city, street) VALUES (3, 'Berlin', 'New Street 15');
INSERT INTO RENT_STATION(id, city, street) VALUES (4, 'New York', 'Old Street 5');
INSERT INTO RENT_STATION(id, city, street) VALUES (5, 'London', 'High Street 10');
INSERT INTO RENT_STATION(id, city, street) VALUES (6, 'Paris', 'Low Street 33');
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (1, 1, 'Scott', 'Blue', 1025814);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (2, 1, 'Kona', 'White', 1025815);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (3, 1, 'Marin', 'Black', 1025816);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (4, 1, 'Giant', 'Red', 1025817);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (5, 1, 'Cannondale', 'Blue', 1025818);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (6, 1, 'Trek', 'White', 1025819);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (7, 1, 'Scott', 'Black', 1025820);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (8, 1, 'Kona', 'Red', 1025821);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (9, 1, 'Marin', 'Blue', 1025822);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (10, 2, 'Giant', 'White', 1025823);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (11, 2, 'Cannondale', 'Black', 1025824);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (12, 2, 'Trek', 'Red', 1025825);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (13, 2, 'Scott', 'Blue', 1025826);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (14, 2, 'Kona', 'White', 1025827);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (15, 2, 'Marin', 'Black', 1025828);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (16, 2, 'Giant', 'Red', 1025829);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (17, 2, 'Cannondale', 'Blue', 1025830);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (18, 2, 'Trek', 'White', 1025831);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (19, 2, 'Scott', 'Black', 1025832);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (20, 3, 'Kona', 'Red', 1025833);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (21, 3, 'Marin', 'Blue', 1025834);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (22, 3, 'Giant', 'White', 1025835);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (23, 3, 'Cannondale', 'Black', 1025836);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (24, 3, 'Trek', 'Red', 1025837);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (25, 3, 'Scott', 'Blue', 1025838);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (26, 3, 'Kona', 'White', 1025839);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (27, 3, 'Marin', 'Black', 1025840);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (28, 3, 'Giant', 'Red', 1025841);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (29, 3, 'Cannondale', 'Blue', 1025842);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (30, 4, 'Trek', 'White', 1025843);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (31, 4, 'Scott', 'Black', 1025844);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (32, 4, 'Kona', 'Red', 1025845);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (33, 4, 'Marin', 'Blue', 1025846);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (34, 4, 'Giant', 'White', 1025847);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (35, 4, 'Cannondale', 'Black', 1025848);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (36, 4, 'Trek', 'Red', 1025849);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (37, 4, 'Scott', 'Blue', 1025850);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (38, 4, 'Kona', 'White', 1025851);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (39, 4, 'Marin', 'Black', 1025852);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (40, 5, 'Giant', 'Red', 1025853);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (41, 5, 'Cannondale', 'Blue', 1025854);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (42, 5, 'Trek', 'White', 1025855);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (43, 5, 'Scott', 'Black', 1025856);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (44, 5, 'Kona', 'Red', 1025857);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (45, 5, 'Marin', 'Blue', 1025858);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (46, 5, 'Giant', 'White', 1025859);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (47, 5, 'Cannondale', 'Black', 1025860);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (48, 5, 'Trek', 'Red', 1025861);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (49, 5, 'Scott', 'Blue', 1025862);
INSERT INTO BIKE(id, rent_station_id, model, color, pin) VALUES (50, 6, 'Kona', 'White', 1025863);
